[rule.type]
level = "error"
options = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
    "release",
]

[rule.scope]
level = "warning"

[rule.description]
level = "error"
min_length = 10
max_length = 72
