// Font Awesome path data, rendered at build time by Icon.astro — same icon set
// the Angular site used, but with zero client-side JS.
import {
  faArrowRight,
  faBars,
  faBolt,
  faBook,
  faBookOpen,
  faCircleQuestion,
  faCube,
  faCubes,
  faDatabase,
  faDiagramProject,
  faFileLines,
  faGauge,
  faGaugeHigh,
  faNetworkWired,
  faPlug,
  faPuzzlePiece,
  faRobot,
  faRocket,
  faServer,
  faShieldHalved,
  faSitemap,
  faUsers,
  faWrench,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { faGithub, faRust } from '@fortawesome/free-brands-svg-icons';

export const icons = {
  'arrow-right': faArrowRight,
  bars: faBars,
  bolt: faBolt,
  book: faBook,
  'book-open': faBookOpen,
  'circle-question': faCircleQuestion,
  cube: faCube,
  cubes: faCubes,
  database: faDatabase,
  'diagram-project': faDiagramProject,
  'file-lines': faFileLines,
  gauge: faGauge,
  'gauge-high': faGaugeHigh,
  github: faGithub,
  'network-wired': faNetworkWired,
  plug: faPlug,
  'puzzle-piece': faPuzzlePiece,
  robot: faRobot,
  rocket: faRocket,
  rust: faRust,
  server: faServer,
  'shield-halved': faShieldHalved,
  sitemap: faSitemap,
  users: faUsers,
  wrench: faWrench,
  xmark: faXmark,
} as const;

export type IconName = keyof typeof icons;
